<div class="wrap amarkal-options" dir="ltr">
    <form method="post" id="ao-form">
        <?php $this->header->render(true); ?>
        <div class="sections">
            <?php foreach( $this->sections as $section ): ?>
                <?php $section->render(true); ?>
            <?php endforeach; ?>
        </div>
        <?php $this->footer->render(true); ?>
        <!-- Subfooter -->
        <?php if( '' != $this->subfooter_text ): ?>
            <div class="ao-subfooter">
                <p><?php echo $this->subfooter_text; ?></p>
            </div>
        <?php endif; ?>
        <input id="options-state" name="state" type="hidden" value="<?php echo htmlspecialchars( json_encode( \Amarkal\Extensions\WordPress\Options\State::get() ) ) ?>" />
    </form>
</div>