<div class="afw-ui-component afw-ui-component-wp-attachment<?php echo ($this->disabled ? ' afw-ui-component-disabled' : '') ?>"
     data-name="<?php echo $this->name; ?>"
     data-value="<?php echo $this->value; ?>">
    <input type="hidden" name="<?php echo $this->name ?>" value="<?php echo $this->value ?>"/>
    <div class="afw-ui-attachment-button"><?php echo $this->value ? 'Change' : 'Choose'?> attachment</div>
    <?php echo wp_get_attachment_image( $this->value ); ?>
</div>