<div class="wrap">
    <h2></h2>
</div>

<div class="clear"></div>
<div class="wrap">
    <table class="ao-wrapper" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td class="ao-content">
                    <form method="post" id="ao-form">

                        <!-- Header -->
                        <div class="ao-header">
                            <img class="icon" src="<?php echo $this->header['icon']; ?>" height="64"/>
                            <h2><?php echo $this->header['title']; ?><span><?php echo $this->header['version']; ?></span></h2>
                            <?php if( isset( $this->header['subtitle'] ) ): ?>
                                <p><?php echo $this->header['subtitle']; ?></p>
                            <?php endif; ?>
                        </div>

                        <!-- Body -->
                        <div class="ao-body">

                            <!-- Sections -->
                            <div class="ao-sections">
                                <?php foreach( $this->options['sections'] as $section ): ?>
                                    <?php $section->render(); ?>
                                <?php endforeach; ?>
                            </div>
                        </div>

                        <!-- Footer -->
                        <div class="ao-footer">
                            <?php if( isset( $this->footer['icon'] ) ): ?>
                                <img class="icon" src="<?php echo $this->footer['icon']; ?>" height="30"/>
                            <?php endif; ?>
                            <p><?php echo $this->footer['text']; ?></p>
                            <div class="ao-control">
                                <button class="button" type="submit" name="submit" class="button" value="save"><i class="fa fa-save"></i> Save</button>
                                <button class="button" type="submit" name="submit" class="button" value="reset-section"><i class="fa fa-mail-reply"></i> Reset Section</button>
                                <button class="button" type="submit" name="submit" class="button" value="reset-all"><i class="fa fa-refresh"></i> Reset All</button>
                            </div>
                        </div>
                    </form>
                </td>

                <!-- Sidebar -->
                <?php if( count($this->options['sections']) > 1 ) : ?>
                    <td class="ao-sidebar">
                        <ul class="ao-section-list">
                            <?php foreach( $this->options['sections'] as $section ): ?>
                                <li class="item<?php echo $section->is_current_section() ? ' active' : ''; ?>">
                                    <a href="?page=<?php echo $this->page_slug; ?>&section=<?php echo $section->get_slug(); ?>" data-slug="<?php echo $section->get_slug(); ?>">
                                        <i class="<?php echo $section->get_icon_class(); ?>"></i>
                                        <span><?php echo $section->title; ?></span>
                                    </a>
                                    
                                    <!-- Tabbed section -->
                                    <?php if( $section instanceof Amarkal\Options\TabbedSection ): ?>
                                        <ul class="tabs">
                                            <?php foreach( $section->get_tabs() as $tab ): ?>
                                            <li>
                                                <?php $tab_slug = Amarkal\Common\Tools::strtoslug($tab); ?>
                                                <?php $href = '?page='.$this->page_slug.'&section='.$section->get_slug().'&tab='.$tab_slug; ?>
                                                <a href="<?php echo $href; ?>" data-parent="<?php echo $section->get_slug(); ?>" data-tab="<?php echo $tab_slug; ?>">
                                                    <i class="<?php echo $section->get_icon_class(); ?>"></i>
                                                    <span><?php echo $tab; ?></span>
                                                </a>
                                            </li>
                                            <?php endforeach; ?>
                                            <li>
                                                <a href="<?php echo '?page='.$this->page_slug.'&section='.$section->get_slug(); ?>" data-parent="<?php echo $section->get_slug(); ?>" data-tab="create">
                                                    <i class="fa fa-plus"></i>
                                                    <span>Add New <?php echo $section->labels['singular']; ?></span>
                                                </a>
                                            </li>
                                        </ul>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                            <li class="item">
                                <a href="collapse">
                                    <i class="fa fa-arrow-circle-right"></i>
                                    <span>Collapse Menu</span>
                                </a>
                            </li>
                        </ul>
                    </td>
                <?php endif; ?>
            </tr>
        </tbody>
    </table>
    
    <!-- Subfooter -->
    <?php if( isset( $this->subfooter['text'] ) ): ?>
        <div class="ao-subfooter">
            <p><?php echo $this->subfooter['text']; ?></p>
        </div>
    <?php endif; ?>
</div>