<div class="<?php echo $this->class; ?><?php echo $this->current_section ? ' active' : ''; ?>" id="<?php echo $this->slug; ?>">

    <?php do_action('ao_notices'); ?>

    <div class="section-header">
        <h3><i class="<?php echo $this->icon; ?>"></i><?php echo $this->title; ?></h3>
        <p><?php echo $this->description; ?></p>
    </div>

    <?php foreach( $this->fields as $field ): ?>
        <div class="field-wrapper<?php echo ($field->disabled ? ' disabled' : ''); ?>">
            <?php if( !$field->full_width ) : ?>
                <div class="field-title">
                    <p class="title"><?php echo $field->title; ?></p>
                    <?php if ( $field->help ): ?>
                        <a class="help" data-toggle="tooltip" data-type="help" data-placement="bottom" title="<?php echo $field->help; ?>">?</a>
                    <?php endif; ?>
                    <?php if ( $field->description ): ?>
                        <p class="description"><?php echo $field->description; ?></p>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <div class="field<?php echo $field->full_width ? ' full-width' : '' ?>">
                <?php echo $field->render(); ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>