<div class="ao-field-switcher <?php echo ($this->multivalue ? 'multivalue' : 'singlevalue'); ?>">
    <input 
        type="text"
        id="<?php echo $this->name; ?>"
        name="<?php echo $this->name; ?>"
        value="<?php echo $this->value; ?>"
        <?php echo ($this->disabled ? 'disabled' : ''); ?>/>
    <?php foreach( $this->labels as $label ) : ?>
        <label data-value="<?php echo $label; ?>" <?php echo (in_array($label, explode(',',$this->value)) ? 'class="active"' : ''); ?>><?php echo $label; ?></label>
    <?php endforeach; ?>
</div>