<div class="afw-wp-meta-box">
    <?php foreach( $this->get_components() as $component ): ?>
        <div class="afw-wp-meta-box-row">
            <div class="afw-wp-meta-box-component-label">
                <label for="<?php echo $component->name; ?>"><?php echo $component->title; ?></label>
                <?php if( $component->description ): ?>
                    <p class="description"><?php echo $component->description; ?></p>
                <?php endif; ?>
            </div>
            <div class="afw-wp-meta-box-component-wrapper">
                <?php $component->render( true ); ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>