<!DOCTYPE html>
<html>
    <head>
        <?php //wp_head(); ?>
        <link rel="stylesheet" type="text/css" href="<?php echo AMARKAL_ASSETS_URL; ?>css/amarkal.min.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo AMARKAL_ASSETS_URL; ?>css/select2.min.css" />
        <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" />
        
        <!-- is there a better way of doing this? -->
        <script src="<?php echo admin_url(); ?>load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate&ver=<?php global $wp_version; echo $wp_version ?>"></script>
        <script src="<?php echo admin_url(); ?>load-scripts.php?c=1&load%5B%5D=jquery-query,jquery-color,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&load%5B%5D=-playlist,jquery-ui-draggable,jquery-ui-slider,jquery-touch-punch,ir&load%5B%5D=is,wp-color-picker,jquery-ui-datepicker,jquery-ui-button,jquery-ui-spinner,jquery-ui-resizable&load%5B%5D=load&ver=<?php global $wp_version; echo $wp_version ?>"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js" ></script>
        <script src="<?php echo AMARKAL_ASSETS_URL; ?>js/select2.min.js" ></script>
        <script src="<?php echo AMARKAL_ASSETS_URL; ?>js/amarkal.min.js" ></script>
    </head>
    <body style="background-color: #f5f5f5;">
        <table class="afw-editor-popup-form">
            <?php foreach( $this->get_components() as $component ): ?>
                <tr class="afw-form-row">
                    <?php if ( !$component->full ): ?>
                        <td class="afw-form-component-label">
                            <?php if ( $component->help ): ?>
                                <a class="help" data-toggle="tooltip" data-type="help" data-placement="right" title="<?php echo htmlspecialchars($component->help); ?>">?</a>
                            <?php endif; ?>
                            <label for="<?php echo $component->name; ?>"><?php echo $component->title; ?></label>
                            <?php if ( $component->description ): ?>
                                <p class="description"><?php echo $component->description; ?></p>
                            <?php endif; ?>
                        </td>
                    <?php endif; ?>
                    <td class="afw-form-component-wrapper" <?php echo $component->full ? 'colspan="2"' : ''; ?>>
                        <?php echo $component->render( $echo ); ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </body>
</html>
