<div class="afw-ui-component afw-ui-component-checkbox<?php echo ($this->disabled ? ' afw-ui-component-disabled' : '') ?>"
     data-name="<?php echo $this->name; ?>"
     data-value="<?php echo $this->value; ?>">
    <input type="hidden" name="<?php echo $this->name; ?>" value="<?php echo $this->value; ?>"/>
    <?php $values = explode( ',', $this->value ); ?>
    <?php foreach( $this->options as $value => $label ) : ?>
        <label>
            <input type="checkbox" 
                   value="<?php echo $value ?>"
                   <?php echo ( in_array( $value, $values ) ? 'checked' : ''); ?>
                   <?php echo ( $this->disabled ? 'disabled' : '' ); ?>/>
            <?php echo $label ?>
        </label>
    <?php endforeach; ?>
</div>