<div class="afw-ui-component afw-ui-component-textarea<?php echo $this->invalid ? ' afw-ui-component-error' : '' ?><?php echo ($this->disabled ? ' afw-ui-component-disabled' : '') ?>"
     data-name="<?php echo $this->name; ?>"
     data-value="<?php echo htmlentities( $this->value ); ?>">
    <textarea
        id="<?php echo $this->name; ?>"
        name="<?php echo $this->name; ?>"
        placeholder="<?php echo $this->placeholder; ?>"
        <?php echo ($this->disabled ? 'disabled' : ''); ?>><?php echo $this->value; ?></textarea>
</div>